// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/money.proto

package protobuf_demo;

public final class MyDataInfo {
    private MyDataInfo() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface UserOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protobuf.User)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string user_name = 1;</code>
         *
         * @return Whether the userName field is set.
         */
        boolean hasUserName();

        /**
         * <code>optional string user_name = 1;</code>
         *
         * @return The userName.
         */
        java.lang.String getUserName();

        /**
         * <code>optional string user_name = 1;</code>
         *
         * @return The bytes for userName.
         */
        com.google.protobuf.ByteString
        getUserNameBytes();

        /**
         * <code>optional int32 user_id = 2;</code>
         *
         * @return Whether the userId field is set.
         */
        boolean hasUserId();

        /**
         * <code>optional int32 user_id = 2;</code>
         *
         * @return The userId.
         */
        int getUserId();

        /**
         * <code>optional string user_addr = 3;</code>
         *
         * @return Whether the userAddr field is set.
         */
        boolean hasUserAddr();

        /**
         * <code>optional string user_addr = 3;</code>
         *
         * @return The userAddr.
         */
        java.lang.String getUserAddr();

        /**
         * <code>optional string user_addr = 3;</code>
         *
         * @return The bytes for userAddr.
         */
        com.google.protobuf.ByteString
        getUserAddrBytes();
    }

    /**
     * Protobuf type {@code protobuf.User}
     */
    public static final class User extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:protobuf.User)
            UserOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use User.newBuilder() to construct.
        private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private User() {
            userName_ = "";
            userAddr_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new User();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private User(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            userName_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            userId_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            userAddr_ = bs;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return protobuf_demo.MyDataInfo.internal_static_protobuf_User_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return protobuf_demo.MyDataInfo.internal_static_protobuf_User_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            protobuf_demo.MyDataInfo.User.class, protobuf_demo.MyDataInfo.User.Builder.class);
        }

        private int bitField0_;
        public static final int USER_NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object userName_;

        /**
         * <code>optional string user_name = 1;</code>
         *
         * @return Whether the userName field is set.
         */
        public boolean hasUserName() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>optional string user_name = 1;</code>
         *
         * @return The userName.
         */
        public java.lang.String getUserName() {
            java.lang.Object ref = userName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    userName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string user_name = 1;</code>
         *
         * @return The bytes for userName.
         */
        public com.google.protobuf.ByteString
        getUserNameBytes() {
            java.lang.Object ref = userName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                userName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int USER_ID_FIELD_NUMBER = 2;
        private int userId_;

        /**
         * <code>optional int32 user_id = 2;</code>
         *
         * @return Whether the userId field is set.
         */
        public boolean hasUserId() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>optional int32 user_id = 2;</code>
         *
         * @return The userId.
         */
        public int getUserId() {
            return userId_;
        }

        public static final int USER_ADDR_FIELD_NUMBER = 3;
        private volatile java.lang.Object userAddr_;

        /**
         * <code>optional string user_addr = 3;</code>
         *
         * @return Whether the userAddr field is set.
         */
        public boolean hasUserAddr() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>optional string user_addr = 3;</code>
         *
         * @return The userAddr.
         */
        public java.lang.String getUserAddr() {
            java.lang.Object ref = userAddr_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    userAddr_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string user_addr = 3;</code>
         *
         * @return The bytes for userAddr.
         */
        public com.google.protobuf.ByteString
        getUserAddrBytes() {
            java.lang.Object ref = userAddr_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                userAddr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeInt32(2, userId_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userAddr_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, userId_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userAddr_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof protobuf_demo.MyDataInfo.User)) {
                return super.equals(obj);
            }
            protobuf_demo.MyDataInfo.User other = (protobuf_demo.MyDataInfo.User) obj;

            if (hasUserName() != other.hasUserName()) return false;
            if (hasUserName()) {
                if (!getUserName()
                        .equals(other.getUserName())) return false;
            }
            if (hasUserId() != other.hasUserId()) return false;
            if (hasUserId()) {
                if (getUserId()
                        != other.getUserId()) return false;
            }
            if (hasUserAddr() != other.hasUserAddr()) return false;
            if (hasUserAddr()) {
                if (!getUserAddr()
                        .equals(other.getUserAddr())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasUserName()) {
                hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
                hash = (53 * hash) + getUserName().hashCode();
            }
            if (hasUserId()) {
                hash = (37 * hash) + USER_ID_FIELD_NUMBER;
                hash = (53 * hash) + getUserId();
            }
            if (hasUserAddr()) {
                hash = (37 * hash) + USER_ADDR_FIELD_NUMBER;
                hash = (53 * hash) + getUserAddr().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.User parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static protobuf_demo.MyDataInfo.User parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static protobuf_demo.MyDataInfo.User parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(protobuf_demo.MyDataInfo.User prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code protobuf.User}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protobuf.User)
                protobuf_demo.MyDataInfo.UserOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return protobuf_demo.MyDataInfo.internal_static_protobuf_User_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return protobuf_demo.MyDataInfo.internal_static_protobuf_User_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                protobuf_demo.MyDataInfo.User.class, protobuf_demo.MyDataInfo.User.Builder.class);
            }

            // Construct using protobuf_demo.MyDataInfo.User.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                userName_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                userId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                userAddr_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return protobuf_demo.MyDataInfo.internal_static_protobuf_User_descriptor;
            }

            @java.lang.Override
            public protobuf_demo.MyDataInfo.User getDefaultInstanceForType() {
                return protobuf_demo.MyDataInfo.User.getDefaultInstance();
            }

            @java.lang.Override
            public protobuf_demo.MyDataInfo.User build() {
                protobuf_demo.MyDataInfo.User result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public protobuf_demo.MyDataInfo.User buildPartial() {
                protobuf_demo.MyDataInfo.User result = new protobuf_demo.MyDataInfo.User(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.userName_ = userName_;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.userId_ = userId_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.userAddr_ = userAddr_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof protobuf_demo.MyDataInfo.User) {
                    return mergeFrom((protobuf_demo.MyDataInfo.User) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(protobuf_demo.MyDataInfo.User other) {
                if (other == protobuf_demo.MyDataInfo.User.getDefaultInstance()) return this;
                if (other.hasUserName()) {
                    bitField0_ |= 0x00000001;
                    userName_ = other.userName_;
                    onChanged();
                }
                if (other.hasUserId()) {
                    setUserId(other.getUserId());
                }
                if (other.hasUserAddr()) {
                    bitField0_ |= 0x00000004;
                    userAddr_ = other.userAddr_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                protobuf_demo.MyDataInfo.User parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (protobuf_demo.MyDataInfo.User) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object userName_ = "";

            /**
             * <code>optional string user_name = 1;</code>
             *
             * @return Whether the userName field is set.
             */
            public boolean hasUserName() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>optional string user_name = 1;</code>
             *
             * @return The userName.
             */
            public java.lang.String getUserName() {
                java.lang.Object ref = userName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        userName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string user_name = 1;</code>
             *
             * @return The bytes for userName.
             */
            public com.google.protobuf.ByteString
            getUserNameBytes() {
                java.lang.Object ref = userName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    userName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string user_name = 1;</code>
             *
             * @param value The userName to set.
             * @return This builder for chaining.
             */
            public Builder setUserName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                userName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string user_name = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUserName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                userName_ = getDefaultInstance().getUserName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string user_name = 1;</code>
             *
             * @param value The bytes for userName to set.
             * @return This builder for chaining.
             */
            public Builder setUserNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                userName_ = value;
                onChanged();
                return this;
            }

            private int userId_;

            /**
             * <code>optional int32 user_id = 2;</code>
             *
             * @return Whether the userId field is set.
             */
            public boolean hasUserId() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional int32 user_id = 2;</code>
             *
             * @return The userId.
             */
            public int getUserId() {
                return userId_;
            }

            /**
             * <code>optional int32 user_id = 2;</code>
             *
             * @param value The userId to set.
             * @return This builder for chaining.
             */
            public Builder setUserId(int value) {
                bitField0_ |= 0x00000002;
                userId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 user_id = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUserId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                userId_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object userAddr_ = "";

            /**
             * <code>optional string user_addr = 3;</code>
             *
             * @return Whether the userAddr field is set.
             */
            public boolean hasUserAddr() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>optional string user_addr = 3;</code>
             *
             * @return The userAddr.
             */
            public java.lang.String getUserAddr() {
                java.lang.Object ref = userAddr_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        userAddr_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string user_addr = 3;</code>
             *
             * @return The bytes for userAddr.
             */
            public com.google.protobuf.ByteString
            getUserAddrBytes() {
                java.lang.Object ref = userAddr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    userAddr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string user_addr = 3;</code>
             *
             * @param value The userAddr to set.
             * @return This builder for chaining.
             */
            public Builder setUserAddr(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                userAddr_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string user_addr = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUserAddr() {
                bitField0_ = (bitField0_ & ~0x00000004);
                userAddr_ = getDefaultInstance().getUserAddr();
                onChanged();
                return this;
            }

            /**
             * <code>optional string user_addr = 3;</code>
             *
             * @param value The bytes for userAddr to set.
             * @return This builder for chaining.
             */
            public Builder setUserAddrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                userAddr_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:protobuf.User)
        }

        // @@protoc_insertion_point(class_scope:protobuf.User)
        private static final protobuf_demo.MyDataInfo.User DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new protobuf_demo.MyDataInfo.User();
        }

        public static protobuf_demo.MyDataInfo.User getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<User>
                PARSER = new com.google.protobuf.AbstractParser<User>() {
            @java.lang.Override
            public User parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new User(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<User> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<User> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public protobuf_demo.MyDataInfo.User getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ResponseBackOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protobuf.ResponseBack)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string back_name = 1;</code>
         *
         * @return Whether the backName field is set.
         */
        boolean hasBackName();

        /**
         * <code>optional string back_name = 1;</code>
         *
         * @return The backName.
         */
        java.lang.String getBackName();

        /**
         * <code>optional string back_name = 1;</code>
         *
         * @return The bytes for backName.
         */
        com.google.protobuf.ByteString
        getBackNameBytes();

        /**
         * <code>optional int32 back_money = 2;</code>
         *
         * @return Whether the backMoney field is set.
         */
        boolean hasBackMoney();

        /**
         * <code>optional int32 back_money = 2;</code>
         *
         * @return The backMoney.
         */
        int getBackMoney();
    }

    /**
     * Protobuf type {@code protobuf.ResponseBack}
     */
    public static final class ResponseBack extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:protobuf.ResponseBack)
            ResponseBackOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ResponseBack.newBuilder() to construct.
        private ResponseBack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ResponseBack() {
            backName_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new ResponseBack();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ResponseBack(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            backName_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            backMoney_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return protobuf_demo.MyDataInfo.internal_static_protobuf_ResponseBack_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return protobuf_demo.MyDataInfo.internal_static_protobuf_ResponseBack_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            protobuf_demo.MyDataInfo.ResponseBack.class, protobuf_demo.MyDataInfo.ResponseBack.Builder.class);
        }

        private int bitField0_;
        public static final int BACK_NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object backName_;

        /**
         * <code>optional string back_name = 1;</code>
         *
         * @return Whether the backName field is set.
         */
        public boolean hasBackName() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>optional string back_name = 1;</code>
         *
         * @return The backName.
         */
        public java.lang.String getBackName() {
            java.lang.Object ref = backName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    backName_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string back_name = 1;</code>
         *
         * @return The bytes for backName.
         */
        public com.google.protobuf.ByteString
        getBackNameBytes() {
            java.lang.Object ref = backName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                backName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BACK_MONEY_FIELD_NUMBER = 2;
        private int backMoney_;

        /**
         * <code>optional int32 back_money = 2;</code>
         *
         * @return Whether the backMoney field is set.
         */
        public boolean hasBackMoney() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>optional int32 back_money = 2;</code>
         *
         * @return The backMoney.
         */
        public int getBackMoney() {
            return backMoney_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, backName_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeInt32(2, backMoney_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, backName_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, backMoney_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof protobuf_demo.MyDataInfo.ResponseBack)) {
                return super.equals(obj);
            }
            protobuf_demo.MyDataInfo.ResponseBack other = (protobuf_demo.MyDataInfo.ResponseBack) obj;

            if (hasBackName() != other.hasBackName()) return false;
            if (hasBackName()) {
                if (!getBackName()
                        .equals(other.getBackName())) return false;
            }
            if (hasBackMoney() != other.hasBackMoney()) return false;
            if (hasBackMoney()) {
                if (getBackMoney()
                        != other.getBackMoney()) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasBackName()) {
                hash = (37 * hash) + BACK_NAME_FIELD_NUMBER;
                hash = (53 * hash) + getBackName().hashCode();
            }
            if (hasBackMoney()) {
                hash = (37 * hash) + BACK_MONEY_FIELD_NUMBER;
                hash = (53 * hash) + getBackMoney();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static protobuf_demo.MyDataInfo.ResponseBack parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(protobuf_demo.MyDataInfo.ResponseBack prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code protobuf.ResponseBack}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protobuf.ResponseBack)
                protobuf_demo.MyDataInfo.ResponseBackOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return protobuf_demo.MyDataInfo.internal_static_protobuf_ResponseBack_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return protobuf_demo.MyDataInfo.internal_static_protobuf_ResponseBack_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                protobuf_demo.MyDataInfo.ResponseBack.class, protobuf_demo.MyDataInfo.ResponseBack.Builder.class);
            }

            // Construct using protobuf_demo.MyDataInfo.ResponseBack.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                backName_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                backMoney_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return protobuf_demo.MyDataInfo.internal_static_protobuf_ResponseBack_descriptor;
            }

            @java.lang.Override
            public protobuf_demo.MyDataInfo.ResponseBack getDefaultInstanceForType() {
                return protobuf_demo.MyDataInfo.ResponseBack.getDefaultInstance();
            }

            @java.lang.Override
            public protobuf_demo.MyDataInfo.ResponseBack build() {
                protobuf_demo.MyDataInfo.ResponseBack result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public protobuf_demo.MyDataInfo.ResponseBack buildPartial() {
                protobuf_demo.MyDataInfo.ResponseBack result = new protobuf_demo.MyDataInfo.ResponseBack(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.backName_ = backName_;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.backMoney_ = backMoney_;
                    to_bitField0_ |= 0x00000002;
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof protobuf_demo.MyDataInfo.ResponseBack) {
                    return mergeFrom((protobuf_demo.MyDataInfo.ResponseBack) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(protobuf_demo.MyDataInfo.ResponseBack other) {
                if (other == protobuf_demo.MyDataInfo.ResponseBack.getDefaultInstance()) return this;
                if (other.hasBackName()) {
                    bitField0_ |= 0x00000001;
                    backName_ = other.backName_;
                    onChanged();
                }
                if (other.hasBackMoney()) {
                    setBackMoney(other.getBackMoney());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                protobuf_demo.MyDataInfo.ResponseBack parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (protobuf_demo.MyDataInfo.ResponseBack) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.lang.Object backName_ = "";

            /**
             * <code>optional string back_name = 1;</code>
             *
             * @return Whether the backName field is set.
             */
            public boolean hasBackName() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>optional string back_name = 1;</code>
             *
             * @return The backName.
             */
            public java.lang.String getBackName() {
                java.lang.Object ref = backName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        backName_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string back_name = 1;</code>
             *
             * @return The bytes for backName.
             */
            public com.google.protobuf.ByteString
            getBackNameBytes() {
                java.lang.Object ref = backName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    backName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string back_name = 1;</code>
             *
             * @param value The backName to set.
             * @return This builder for chaining.
             */
            public Builder setBackName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                backName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string back_name = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearBackName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                backName_ = getDefaultInstance().getBackName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string back_name = 1;</code>
             *
             * @param value The bytes for backName to set.
             * @return This builder for chaining.
             */
            public Builder setBackNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                backName_ = value;
                onChanged();
                return this;
            }

            private int backMoney_;

            /**
             * <code>optional int32 back_money = 2;</code>
             *
             * @return Whether the backMoney field is set.
             */
            public boolean hasBackMoney() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional int32 back_money = 2;</code>
             *
             * @return The backMoney.
             */
            public int getBackMoney() {
                return backMoney_;
            }

            /**
             * <code>optional int32 back_money = 2;</code>
             *
             * @param value The backMoney to set.
             * @return This builder for chaining.
             */
            public Builder setBackMoney(int value) {
                bitField0_ |= 0x00000002;
                backMoney_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 back_money = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearBackMoney() {
                bitField0_ = (bitField0_ & ~0x00000002);
                backMoney_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:protobuf.ResponseBack)
        }

        // @@protoc_insertion_point(class_scope:protobuf.ResponseBack)
        private static final protobuf_demo.MyDataInfo.ResponseBack DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new protobuf_demo.MyDataInfo.ResponseBack();
        }

        public static protobuf_demo.MyDataInfo.ResponseBack getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<ResponseBack>
                PARSER = new com.google.protobuf.AbstractParser<ResponseBack>() {
            @java.lang.Override
            public ResponseBack parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ResponseBack(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ResponseBack> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ResponseBack> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public protobuf_demo.MyDataInfo.ResponseBack getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protobuf_User_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protobuf_User_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protobuf_ResponseBack_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protobuf_ResponseBack_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\035src/main/protobuf/money.proto\022\010protobu" +
                        "f\"=\n\004User\022\021\n\tuser_name\030\001 \001(\t\022\017\n\007user_id\030" +
                        "\002 \001(\005\022\021\n\tuser_addr\030\003 \001(\t\"5\n\014ResponseBack" +
                        "\022\021\n\tback_name\030\001 \001(\t\022\022\n\nback_money\030\002 \001(\005B" +
                        "\035\n\rprotobuf_demoB\nMyDataInfoH\001"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_protobuf_User_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_protobuf_User_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protobuf_User_descriptor,
                new java.lang.String[]{"UserName", "UserId", "UserAddr",});
        internal_static_protobuf_ResponseBack_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_protobuf_ResponseBack_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protobuf_ResponseBack_descriptor,
                new java.lang.String[]{"BackName", "BackMoney",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
